(() => {
  const PLACE={name:'North Haven, Maine',lat:44.1304,lon:-68.8742,tz:'America/New_York'};
  const API=`https://api.open-meteo.com/v1/forecast?latitude=${PLACE.lat}&longitude=${PLACE.lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FNew_York&forecast_days=7`;
  const $=id=>document.getElementById(id); let voices=[],weather=null,lastScript='',alternate=0;
  const codes={0:'clear',1:'mostly clear',2:'partly cloudy',3:'overcast',45:'foggy',48:'foggy with frost',51:'light drizzle',53:'drizzle',55:'heavy drizzle',56:'light freezing drizzle',57:'freezing drizzle',61:'light rain',63:'rain',65:'heavy rain',66:'light freezing rain',67:'freezing rain',71:'light snow',73:'snow',75:'heavy snow',77:'snow grains',80:'light rain showers',81:'rain showers',82:'heavy rain showers',85:'light snow showers',86:'heavy snow showers',95:'thunderstorms',96:'thunderstorms with light hail',99:'thunderstorms with hail'};
  const condition=c=>codes[c]||'mixed conditions';
  function timeText(seconds=false){return new Intl.DateTimeFormat('en-US',{timeZone:PLACE.tz,hour:'numeric',minute:'2-digit',second:seconds?'2-digit':undefined}).format(new Date())}
  function tick(){$('clock').textContent=timeText(true)} setInterval(tick,1000);tick();
  async function loadWeather(){
    $('weatherStatus').textContent='Loading weather…';$('refreshWeather').disabled=true;
    try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error(r.status);weather=await r.json();const c=weather.current;$('temperature').textContent=`${Math.round(c.temperature_2m)}°F`;$('conditions').textContent=condition(c.weather_code).replace(/\b\w/g,x=>x.toUpperCase());$('weatherStatus').textContent='Weather updated'}catch(e){console.error(e);weather=null;$('temperature').textContent='Unavailable';$('conditions').textContent='Could not load';$('weatherStatus').textContent='Weather error'}finally{$('refreshWeather').disabled=false}}
  function score(v,kind){const n=v.name.toLowerCase();let s=/^en[-_]?us/i.test(v.lang)?40:/^en/i.test(v.lang)?20:-60;if(v.localService)s+=8;['premium','enhanced','natural','neural','online'].forEach(x=>{if(n.includes(x))s+=8});const male=['alex','daniel','aaron','fred','tom','evan','reed','david','male'];const female=['samantha','victoria','allison','ava','karen','zira','susan','female'];(kind==='male'?male:female).forEach(x=>{if(n.includes(x))s+=18});return s}
  function populate(){voices=speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang)).sort((a,b)=>a.name.localeCompare(b.name));for(const id of ['maleVoice','femaleVoice']){$(id).innerHTML='';voices.forEach((v,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${v.name} — ${v.lang}${v.localService?' · local':''}`;$(id).append(o)})}if(voices.length){$('maleVoice').value=voices.map((v,i)=>({i,s:score(v,'male')})).sort((a,b)=>b.s-a.s)[0].i;$('femaleVoice').value=voices.map((v,i)=>({i,s:score(v,'female')})).sort((a,b)=>b.s-a.s)[0].i;$('speechStatus').textContent=`${voices.length} voices found`}else $('speechStatus').textContent='No English voices found'}
  function settings(force){let p=force||$('activeProfile').value;if(p==='alternate')p=alternate++%2?'female':'male';const male=p==='male';return{p,voice:voices[Number($(male?'maleVoice':'femaleVoice').value)]||voices[0],rate:Number($(male?'maleRate':'femaleRate').value),pitch:Number($(male?'malePitch':'femalePitch').value)}}
  function speak(text,force){if(!text)return;speechSynthesis.cancel();const s=settings(force),u=new SpeechSynthesisUtterance($('gentlePauses').checked?text.replace(/:\s+/g,'. ').replace(/;\s+/g,'. '):text);u.voice=s.voice;u.lang=s.voice?.lang||'en-US';u.rate=s.rate;u.pitch=s.pitch;u.onstart=()=>$('speechStatus').textContent=`Speaking · ${s.p}`;u.onend=()=>$('speechStatus').textContent='Voice ready';u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))$('speechStatus').textContent=`Speech error · ${e.error}`};speechSynthesis.speak(u)}
  function say(text,force){lastScript=text;$('scriptPreview').textContent=text;speak(text,force)}
  function needWeather(){if(weather)return true;say('I could not retrieve the current weather for North Haven. Please refresh the forecast.');return false}
  function dayName(date,i){if(i===0)return'Today';if(i===1)return'Tomorrow';return new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:PLACE.tz}).format(new Date(date+'T12:00:00'))}
  function script(action){if(action==='time')return`The time in North Haven is ${timeText(false)}.`;if(action==='return')return'And now, back to the music.';if(!needWeather())return null;const c=weather.current,d=weather.daily;if(action==='temperature'){const a=Math.round(c.temperature_2m),f=Math.round(c.apparent_temperature);return`Right now in North Haven, it is ${a} degrees and ${condition(c.weather_code)}.${Math.abs(a-f)>=3?` It feels like ${f} degrees.`:''}`}if(action==='today')return`Today in North Haven, expect ${condition(d.weather_code[0])}, with a high near ${Math.round(d.temperature_2m_max[0])} and a low near ${Math.round(d.temperature_2m_min[0])}. The chance of precipitation is ${d.precipitation_probability_max[0]} percent.`;if(action==='extended'){let parts=[];for(let i=0;i<Math.min(4,d.time.length);i++)parts.push(`${dayName(d.time[i],i)}: ${condition(d.weather_code[i])}, with a high of ${Math.round(d.temperature_2m_max[i])} and a low of ${Math.round(d.temperature_2m_min[i])}.`);return`Here is the outlook for North Haven. ${parts.join(' ')}`}if(action==='full')return`It is ${timeText(false)} in North Haven. The temperature is ${Math.round(c.temperature_2m)} degrees, with ${condition(c.weather_code)}. Today’s high will be near ${Math.round(d.temperature_2m_max[0])}. Tomorrow, expect ${condition(d.weather_code[1])}, with a high near ${Math.round(d.temperature_2m_max[1])}. Now, back to the music.`}
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const t=script(b.dataset.action);if(t)say(t)}));
  document.querySelectorAll('[data-line]').forEach(b=>b.addEventListener('click',()=>say(b.dataset.line)));
  document.querySelectorAll('.audition').forEach(b=>b.addEventListener('click',()=>say(b.dataset.profile==='male'?'Good evening. This is a voice calibration for Song Pages. The next song will begin in just a moment.':'Good evening. You’re listening to Song Pages from North Haven, Maine. We’ll return to the music in just a moment.',b.dataset.profile)));
  $('speakCustom').addEventListener('click',()=>say($('customText').value));$('speakAgain').addEventListener('click',()=>lastScript&&speak(lastScript));$('stopSpeech').addEventListener('click',()=>{speechSynthesis.cancel();$('speechStatus').textContent='Stopped'});$('refreshWeather').addEventListener('click',loadWeather);$('refreshVoices').addEventListener('click',populate);
  for(const [input,out] of [['maleRate','maleRateValue'],['malePitch','malePitchValue'],['femaleRate','femaleRateValue'],['femalePitch','femalePitchValue']]){const sync=()=>$(out).textContent=Number($(input).value).toFixed(2);$(input).addEventListener('input',sync);sync()}
  populate();speechSynthesis.onvoiceschanged=populate;loadWeather();
})();
