/** Generated by scripts/generate-kudo-asset-catalog.mjs — do not edit. */
import asset_808_single_color from '../../assets/images/kudo-images/808-single-color-image.png';
import asset_808_grays from '../../assets/images/kudo-images/808-grays-image.png';
import asset_album_single_color from '../../assets/images/kudo-images/album-single-color-image.png';
import asset_album_grays from '../../assets/images/kudo-images/album-grays-image.png';
import asset_bolt_single_color from '../../assets/images/kudo-images/bolt-single-color-image.png';
import asset_bolt_grays from '../../assets/images/kudo-images/bolt-grays-image.png';
import asset_bubbles_single_color from '../../assets/images/kudo-images/bubbles-single-color-image.png';
import asset_bubbles_grays from '../../assets/images/kudo-images/bubbles-grays-image.png';
import asset_buzzerx_single_color from '../../assets/images/kudo-images/buzzerx-single-color-image.png';
import asset_buzzerx_grays from '../../assets/images/kudo-images/buzzerx-grays-image.png';
import asset_checkmark_single_color from '../../assets/images/kudo-images/checkmark-single-color-image.png';
import asset_checkmark_grays from '../../assets/images/kudo-images/checkmark-grays-image.png';
import asset_confetti_single_color from '../../assets/images/kudo-images/confetti-single-color-image.png';
import asset_confetti_grays from '../../assets/images/kudo-images/confetti-grays-image.png';
import asset_cutdiamond_single_color from '../../assets/images/kudo-images/cutdiamond-single-color-image.png';
import asset_cutdiamond_grays from '../../assets/images/kudo-images/cutdiamond-grays-image.png';
import asset_diamond_single_color from '../../assets/images/kudo-images/diamond-single-color-image.png';
import asset_diamond_grays from '../../assets/images/kudo-images/diamond-grays-image.png';
import asset_doublenote_single_color from '../../assets/images/kudo-images/doublenote-single-color-image.png';
import asset_doublenote_grays from '../../assets/images/kudo-images/doublenote-grays-image.png';
import asset_downarrow_single_color from '../../assets/images/kudo-images/downarrow-single-color-image.png';
import asset_downarrow_grays from '../../assets/images/kudo-images/downarrow-grays-image.png';
import asset_exclamationpoint_single_color from '../../assets/images/kudo-images/exclamationpoint-single-color-image.png';
import asset_exclamationpoint_grays from '../../assets/images/kudo-images/exclamationpoint-grays-image.png';
import asset_flame_single_color from '../../assets/images/kudo-images/flame-single-color-image.png';
import asset_flame_grays from '../../assets/images/kudo-images/flame-grays-image.png';
import asset_flower1_single_color from '../../assets/images/kudo-images/flower1-single-color-image.png';
import asset_flower1_grays from '../../assets/images/kudo-images/flower1-grays-image.png';
import asset_gclef_single_color from '../../assets/images/kudo-images/gclef-single-color-image.png';
import asset_gclef_grays from '../../assets/images/kudo-images/gclef-grays-image.png';
import asset_handsintheair_single_color from '../../assets/images/kudo-images/handsintheair-single-color-image.png';
import asset_handsintheair_grays from '../../assets/images/kudo-images/handsintheair-grays-image.png';
import asset_heart_single_color from '../../assets/images/kudo-images/heart-single-color-image.png';
import asset_heart_grays from '../../assets/images/kudo-images/heart-grays-image.png';
import asset_hearts_single_color from '../../assets/images/kudo-images/hearts-single-color-image.png';
import asset_hearts_grays from '../../assets/images/kudo-images/hearts-grays-image.png';
import asset_kingcrown_single_color from '../../assets/images/kudo-images/kingcrown-single-color-image.png';
import asset_kingcrown_grays from '../../assets/images/kudo-images/kingcrown-grays-image.png';
import asset_microphone_single_color from '../../assets/images/kudo-images/microphone-single-color-image.png';
import asset_microphone_grays from '../../assets/images/kudo-images/microphone-grays-image.png';
import asset_pianokeys_single_color from '../../assets/images/kudo-images/pianokeys-single-color-image.png';
import asset_pianokeys_grays from '../../assets/images/kudo-images/pianokeys-grays-image.png';
import asset_queencrown_single_color from '../../assets/images/kudo-images/queencrown-single-color-image.png';
import asset_queencrown_grays from '../../assets/images/kudo-images/queencrown-grays-image.png';
import asset_sparkles_single_color from '../../assets/images/kudo-images/sparkles-single-color-image.png';
import asset_sparkles_grays from '../../assets/images/kudo-images/sparkles-grays-image.png';
import asset_star_single_color from '../../assets/images/kudo-images/star-single-color-image.png';
import asset_star_grays from '../../assets/images/kudo-images/star-grays-image.png';
import asset_triplenote_single_color from '../../assets/images/kudo-images/triplenote-single-color-image.png';
import asset_triplenote_grays from '../../assets/images/kudo-images/triplenote-grays-image.png';
import asset_uparrow_single_color from '../../assets/images/kudo-images/uparrow-single-color-image.png';
import asset_uparrow_grays from '../../assets/images/kudo-images/uparrow-grays-image.png';

export type KudoAssetVariant = 'single-color' | 'grays';

export type BuiltInKudoAsset = {
  id: string;
  label: string;
  variants: Partial<Record<KudoAssetVariant, string>>;
};

export const KUDO_ASSET_CATALOG: BuiltInKudoAsset[] = [
  {
    id: '808',
    label: '808',
    variants: {
    'single-color': asset_808_single_color,
    'grays': asset_808_grays,
    },
  },
  {
    id: 'album',
    label: 'Album',
    variants: {
    'single-color': asset_album_single_color,
    'grays': asset_album_grays,
    },
  },
  {
    id: 'bolt',
    label: 'Bolt',
    variants: {
    'single-color': asset_bolt_single_color,
    'grays': asset_bolt_grays,
    },
  },
  {
    id: 'bubbles',
    label: 'Bubbles',
    variants: {
    'single-color': asset_bubbles_single_color,
    'grays': asset_bubbles_grays,
    },
  },
  {
    id: 'buzzerx',
    label: 'Buzzerx',
    variants: {
    'single-color': asset_buzzerx_single_color,
    'grays': asset_buzzerx_grays,
    },
  },
  {
    id: 'checkmark',
    label: 'Checkmark',
    variants: {
    'single-color': asset_checkmark_single_color,
    'grays': asset_checkmark_grays,
    },
  },
  {
    id: 'confetti',
    label: 'Confetti',
    variants: {
    'single-color': asset_confetti_single_color,
    'grays': asset_confetti_grays,
    },
  },
  {
    id: 'cutdiamond',
    label: 'Cutdiamond',
    variants: {
    'single-color': asset_cutdiamond_single_color,
    'grays': asset_cutdiamond_grays,
    },
  },
  {
    id: 'diamond',
    label: 'Diamond',
    variants: {
    'single-color': asset_diamond_single_color,
    'grays': asset_diamond_grays,
    },
  },
  {
    id: 'doublenote',
    label: 'Doublenote',
    variants: {
    'single-color': asset_doublenote_single_color,
    'grays': asset_doublenote_grays,
    },
  },
  {
    id: 'downarrow',
    label: 'Downarrow',
    variants: {
    'single-color': asset_downarrow_single_color,
    'grays': asset_downarrow_grays,
    },
  },
  {
    id: 'exclamationpoint',
    label: 'Exclamationpoint',
    variants: {
    'single-color': asset_exclamationpoint_single_color,
    'grays': asset_exclamationpoint_grays,
    },
  },
  {
    id: 'flame',
    label: 'Flame',
    variants: {
    'single-color': asset_flame_single_color,
    'grays': asset_flame_grays,
    },
  },
  {
    id: 'flower1',
    label: 'Flower1',
    variants: {
    'single-color': asset_flower1_single_color,
    'grays': asset_flower1_grays,
    },
  },
  {
    id: 'gclef',
    label: 'Gclef',
    variants: {
    'single-color': asset_gclef_single_color,
    'grays': asset_gclef_grays,
    },
  },
  {
    id: 'handsintheair',
    label: 'Handsintheair',
    variants: {
    'single-color': asset_handsintheair_single_color,
    'grays': asset_handsintheair_grays,
    },
  },
  {
    id: 'heart',
    label: 'Heart',
    variants: {
    'single-color': asset_heart_single_color,
    'grays': asset_heart_grays,
    },
  },
  {
    id: 'hearts',
    label: 'Hearts',
    variants: {
    'single-color': asset_hearts_single_color,
    'grays': asset_hearts_grays,
    },
  },
  {
    id: 'kingcrown',
    label: 'Kingcrown',
    variants: {
    'single-color': asset_kingcrown_single_color,
    'grays': asset_kingcrown_grays,
    },
  },
  {
    id: 'microphone',
    label: 'Microphone',
    variants: {
    'single-color': asset_microphone_single_color,
    'grays': asset_microphone_grays,
    },
  },
  {
    id: 'pianokeys',
    label: 'Pianokeys',
    variants: {
    'single-color': asset_pianokeys_single_color,
    'grays': asset_pianokeys_grays,
    },
  },
  {
    id: 'queencrown',
    label: 'Queencrown',
    variants: {
    'single-color': asset_queencrown_single_color,
    'grays': asset_queencrown_grays,
    },
  },
  {
    id: 'sparkles',
    label: 'Sparkles',
    variants: {
    'single-color': asset_sparkles_single_color,
    'grays': asset_sparkles_grays,
    },
  },
  {
    id: 'star',
    label: 'Star',
    variants: {
    'single-color': asset_star_single_color,
    'grays': asset_star_grays,
    },
  },
  {
    id: 'triplenote',
    label: 'Triplenote',
    variants: {
    'single-color': asset_triplenote_single_color,
    'grays': asset_triplenote_grays,
    },
  },
  {
    id: 'uparrow',
    label: 'Uparrow',
    variants: {
    'single-color': asset_uparrow_single_color,
    'grays': asset_uparrow_grays,
    },
  },
];

export const KUDO_ASSET_IDS = KUDO_ASSET_CATALOG.map((row) => row.id);

export function findKudoAsset(assetId: string): BuiltInKudoAsset | undefined {
  return KUDO_ASSET_CATALOG.find((row) => row.id === assetId);
}
